# Generated by Django 2.0.2 on 2018-06-27 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Golf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameModel(
            old_name='Job',
            new_name='Jobs',
        ),
    ]
